[package]
name = "netrs"
description = "Userspace networking library and utilities"
version = "0.0.1"
authors = ["wilypomegranate <wilypomegranate@users.noreply.github.com>"]
homepage = "https://github.com/wilypomegranate/netrs"
edition = "2018"
license = "BSD-3-Clause"

[dependencies]
